# Generated by Django 4.1.1 on 2022-10-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbio',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='post',
        ),
        migrations.AddField(
            model_name='userpost',
            name='age',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
